dataset_dir: "robotdata/robotwin_third"
project_dir: '.'
vae_model_path: 'pretrained_models/stabilityai/stable-diffusion-xl-base-1.0'
scheduler_path: 'pretrained_models/stabilityai/stable-diffusion-xl-base-1.0/scheduler'
results_dir: "results/results_roobtwin_third"
annotation_name: 'annotation' # annotation dirname under dataset_dir path
# torchrun --nproc_per_node 4 --nnodes 1 --node_rank 0 --rdzv_endpoint localhost:29502 --rdzv_id 108 --rdzv_backend c10d main.py --config configs/train/robotwin/frame_ada.yaml --data_config data_robotwin.yaml